#!/bin/bash
#
# Debian GNU dlocate(1) completion


_executables(){
    echo -n "$PATH" | xargs -d: -I{} -- find -L {} -maxdepth 1 -type f -executable -printf '%P\n' 2>/dev/null | sort -u
}

_have dlocate && {

_dlocate(){
    local cur prev

    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    case $prev in

    -o)
        COMPREPLY=( $( compgen -W "$(_executables)" -- "$cur" ) )
        return 0
        ;;

    -@(e|S))
        _filedir
        return 0
        ;;

    -@(conf|du|f|l|L|ls|lsbin|lscmd|lsconf|lsman|man|md5check|md5sum|s))
        COMPREPLY=( $( _xfunc dpkg _comp_dpkg_installed_packages "$cur" ) )
        return 0
        ;;

    *)
        optionlist='-conf -d --debug -du -e -f --filename-only -h -H --help -k\
                   -K -l -L -ls -lsbin -lscmd -lsconf -lsman -man -md5check\
                   -md5sum -o -p --package-only -s -S -v -V --verbose --version'
        COMPREPLY=( $( compgen -W "$optionlist" -- "$cur" ) )
        return 0
        ;;

    esac

}

complete -F _dlocate $filenames dlocate

}
